version: '3.7'

services:
  postgres:
    container_name: time-flow-db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=time-flow-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: '.'
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/time-flow-db
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jpa.hibernate.ddl-auto=update
    depends_on:
      - postgres

networks:
  default:
    name: time-flow-api
    driver: bridge
