version: '3.7'

services:
  postgres:
    container_name: time-flow-db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=time-flow-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: '.'
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      - spring_datasource_url=jdbc:postgresql://postgres:5432/time-flow-db
      - spring_datasource_username=postgres
      - spring_datasource_password=postgres
      - spring_jpa_hibernate_ddl-auto=update
      - email_confirm_host=localhost
      - email_confirm_port=8080
    depends_on:
      - postgres

networks:
  default:
    name: time-flow-api
    driver: bridge
