server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/time-flow-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  mandatory-file-encoding: UTF-8
token:
  access.secret-key: access_secret_key
  access.lifetime_min: 15
  refresh.secret-key: refresh_secret_key
  refresh.lifetime_min: 43200
  issuer: time-flow-api
credentials:
  admin:
    email: admin
    password: admin
    name: admin_name
    surname: admin_surname
    patronymic: admin_patronymic