server:
  port: 8080
spring:
  datasource:
    url: ${spring_datasource_url:jdbc:postgresql://postgres:5432/time-flow-db}
    username: ${spring_datasource_username:postgres}
    password: ${spring_datasource_password:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${spring_jpa_hibernate_ddl-auto:update}
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
  mandatory-file-encoding: UTF-8
  mvc:
    dispatch-options-request: true
  mail:
    host: smtp.yandex.ru
    username: time-flow-api@yandex.ru
    password: qmuxknxqqzwmvpdy
    port: 465
    protocol: smtps
    debug: false
secret-key: 1234567812345678
token:
  access:
    secret-key: access_secret_key
    lifetime_min: 15
  refresh:
    secret-key: refresh_secret_key
    lifetime_min: 43200
  issuer: time-flow-api
logging:
  file:
    path: ${path_log_file:./}
    name: ${log_file_name:time-flow-api.log}
  level:
    root: info
email_confirm:
  host: ${email_confirm_host:localhost}
  port: ${email_confirm_port:8080}