server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/time-flow-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
  mandatory-file-encoding: UTF-8
  mvc:
    dispatch-options-request: true
token:
  access.secret-key: access_secret_key
  access.lifetime_min: 15
  refresh.secret-key: refresh_secret_key
  refresh.lifetime_min: 43200
  issuer: time-flow-api
logging:
  file:
    path: ${PATH_LOG_FILE:./}
    name: ${LOG_FILE_NAME:time-flow-api.log}
  level:
    root: info
credentials:
  admin:
    email: admin@gmail.com
    password: password
    name: Иван
    surname: Иванов
    patronymic: Иванович